apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.app }}
spec:
  ports:
    - name: keySRV
      port: 1123
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.service.app }}
  type: {{ .Values.service.type }}
