name: Helm Lint

on:
  push:
    paths:
      - "helm/**"
  pull_request:
    paths:
      - "helm/**"

permissions:
  contents: read

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4 # Or latest available

      - name: Lint Helm chart
        run: helm lint helm/
